### ISSUE TITLE
Chests go translucent with tinker table

### ISSUE THREAD

**Issue by EzerArch** [MachineMuse/MachineMusePowersuits#768] opened 2017-03-25 21:39 UTC
This is a very specific bug. This depends on the direction you are facing and block layout.

Chests will go translucent if:
- there's a beacon.
- there are chests and/or ender chests.
- you place a tinker table between the beacon and the chests.
- you must be standing before the tinker table, facing towards the chests. Not between them.
- not required the beacon be in the FOV.

![2017-03-25_18 19 44](https://cloud.githubusercontent.com/assets/6743303/24326190/bc5af77e-1187-11e7-98e8-2f721b151e99.png)
![2017-03-25_18 19 57](https://cloud.githubusercontent.com/assets/6743303/24326192/c7aed69a-1187-11e7-8482-7ad98c9cbff2.png)
![2017-03-25_18 41 12](https://cloud.githubusercontent.com/assets/6743303/24326325/a42aaf84-118a-11e7-9073-75e7c90af5cc.png)

**Comment by lehjr** [comment] 2017-03-25 22:55
o.0 I think I know what the issue is here. I'll check on this after I figure out the power issue. There's also a rendering bug with the power fist.

**Comment by lehjr** [comment] 2017-04-19 14:39
This seems to be a vanilla rendering glitch. I recreated the tinker table model as a Wavefront model, where Minecraft handles ALL of the rendering, and the glitches are really bad. The first photo is all wavefront models, with a block render setting of ```BlockRenderLayer.TRANSLUCENT```. At some angles, the top of the table disappears. The second photo is the effect bleeding into the actual Tinker Table model nearby despite there being no software changes to the model or block. The only fix would be a completely new model without any translucent layers. 

![2017-04-19_10 21 36](https://cloud.githubusercontent.com/assets/1084367/25185833/631aa038-24ec-11e7-84a9-6212d9122445.png)
![2017-04-19_10 35 13](https://cloud.githubusercontent.com/assets/1084367/25185857/6dbc6620-24ec-11e7-8197-360718259524.png)

**Comment by lehjr** [comment] 2017-04-25 19:30
I found a really old Tinker Table, maybe the original. I might be able to retexture this a bit and use it without the screen on top and without the cube. The screen doesn't even use a texture, but it drawn with just opengl code and still has glitches. 
![2017-04-25_15 22 02](https://cloud.githubusercontent.com/assets/1084367/25403849/bb5339de-29cb-11e7-8752-8b39014f700f.png)

**Comment by eyeonus** [comment] 2017-04-26 00:21
That thing is ugly.

Maybe it would be better to start from scratch, and just not have the floating green thing.

**Comment by eyeonus** [comment] 2017-04-26 00:23
Maybe it has something to do with the model being larger than a block?

**Comment by lehjr** [comment] 2017-04-26 00:25
It seems to be an issue with mixing alpha blending and solids in the same block.

**Comment by eyeonus** [comment] 2017-04-26 00:28
Mmm. That makes sense.

**Comment by lehjr** [comment] 2017-04-26 00:30
Even the wavefront model where Minecraft was handling the rendering had issues. 

Starting from scratch would be better if I really had an idea what direction to go in. All I know is that it needs to be a model with no animations or transparencies. Anything else is going to do the same thing.

**Comment by EzerArch** [comment] 2017-04-26 00:30
Interesting this glitch happens only in certain directions/potions. :S

**Comment by eyeonus** [comment] 2017-04-26 00:38
Well, I have literally no artistic talent, so I can't help you there. Maybe just, in the meantime, remove the alpha stuff?

**Comment by lehjr** [comment] 2017-04-26 00:41
On the directional glitch... even when Minecraft handles the rendering in the Wavefront model, the chests are actually blocked by the screens in some directions but not others just as the top of the tinker table glitches out at different angles.

Turning off the alpha is just as ugly as the other model.

**Comment by eyeonus** [comment] 2017-04-26 00:50
No, no, I meant removing the alpha bits.

**Comment by lehjr** [comment] 2017-04-26 00:52
yeah removing the alpha bits makes it render like it does with graphics set to fast, where the screens are solid green

**Comment by eyeonus** [comment] 2017-04-26 00:56
Okay, I'm obviously not being clear. Not remove alpha from the things that have alpha.

Remove the things that have alpha.

**Comment by lehjr** [comment] 2017-04-26 00:56
![2017-04-25_20 55 32](https://cloud.githubusercontent.com/assets/1084367/25413616/b211166a-29f9-11e7-9f71-7f3cb668413b.png)

**Comment by lehjr** [comment] 2017-04-26 00:57
You can't remove the bits without reworking the model. Half the model uses transparencies.

**Comment by eyeonus** [comment] 2017-04-26 01:01
Yes, that screenshot is precisely what I didn't mean.

Well, yeah, but reworking it is kind of a given though, isn't it?

**Comment by lehjr** [comment] 2017-04-26 01:03
But that's the thing. Reworking it is replacing more than half of it. That's why I was looking at something simple. With simple models, users can replace them with resource packs.

**Comment by eyeonus** [comment] 2017-04-26 01:09
It was just an idea. I figured just deleting the parts that were causing the glitches would be the easiest thing to do, at least until you figure out what you really want.

**Comment by lehjr** [comment] 2017-04-26 01:12
The problem is that it's the top 3 screens, the cube the green part in the middle and the upper table, and maybe the 3 "tanks".  That leaves the base, part of the upper table, and the "wire" parts.

**Comment by lehjr** [comment] 2017-04-26 01:17
This is what it looks like with the problem parts removed ![screenshot from 2017-04-25 21-16-29](https://cloud.githubusercontent.com/assets/1084367/25413977/7a776a6c-29fc-11e7-8f0f-3eddeca2a0d5.png)

**Comment by eyeonus** [comment] 2017-04-26 01:19
I did not know that was a screen. I actually thought it was just the top of the table.

Maybe put that one back but without transparency.

Otherwise, I'd say it looks alright.

Definitely better than gray-and-blue-crafting-table-with-green-floaties.

**Comment by lehjr** [comment] 2017-04-26 01:24
The green parts where the screens. Hmm, I'll have to taker a stab at the textures tomorrow. But I think can fill in that green part in the middle with an opaque color and fill the cube green. The screens will have to stay gone.

**Comment by eyeonus** [comment] 2017-04-26 01:26
No, the thing I'm taking about isn't green. It's mostly black with a couple
blue rectangles.

**Comment by lehjr** [comment] 2017-04-26 01:27
Yeah, but that has a transparency as well around the sides.

**Comment by eyeonus** [comment] 2017-04-26 01:31
Right, yes, I figured it did, that's why I said to leave that one, but without transparency.

Or, if it's easier, move that texture to the top of the table where the weird X thing is.

**Comment by lehjr** [comment] 2017-04-26 01:33
Texture areas don't rescale well for model base models. I'm working on coloring in some areas of the texture.

**Comment by lehjr** [comment] 2017-04-26 01:38
![screenshot from 2017-04-25 21-38-03](https://cloud.githubusercontent.com/assets/1084367/25414462/8ea56d42-29ff-11e7-87bf-9e73cf696f54.png)

**Comment by lehjr** [comment] 2017-04-26 01:39
Needs a bit more work on the gray area in the middle but it's better than it was.

**Comment by eyeonus** [comment] 2017-04-26 01:41
Looks alright to me. Did you mess with the meshes or edit the texture?

**Comment by lehjr** [comment] 2017-04-26 01:42
edited the texture

**Comment by lehjr** [comment] 2017-04-26 01:42
Still have to turn off the alpha stuff in the code though

**Comment by eyeonus** [comment] 2017-04-26 01:42
![tinkertable_tx-alt](https://cloud.githubusercontent.com/assets/1733600/25414576/6455e766-29ef-11e7-860a-b24294c99769.png)
Damn. So did I. Duplication of effort is teh lose.

**Comment by eyeonus** [comment] 2017-04-26 01:46
How do you get Minecraft to do that, btw? The whole model loader thing?

Also, regarding the, um, stump, I never noticed it as a player, so if you made it the same color green, just not transparent, I doubt many people would even notice.

**Comment by lehjr** [comment] 2017-04-26 01:50
In this case, it's still a model base model, so just comment out RenderState.blendingOn(); https://github.com/MachineMuse/MachineMusePowersuits/blob/1.10.2-Java/src/main/java/net/machinemuse/powersuits/client/render/block/TinkerTableModel.java#L188 

and RenderState.blendingOff();

**Comment by lehjr** [comment] 2017-04-26 01:52
and the parts to get rid of get commented out, like the 3 screens.

**Comment by eyeonus** [comment] 2017-04-26 01:52
What? No, I mean the thing you did to Minecraft. In your last screenshot, the program that is running that you took a screenshot of, according to the window title, is Minecraft 1.8.

**Comment by lehjr** [comment] 2017-04-26 01:53
Oh, that. That's Tabula for 1.8.

**Comment by eyeonus** [comment] 2017-04-26 01:54
Oooohhh. And here I thought Minecraft had a secret developer's mode.

**Comment by lehjr** [comment] 2017-04-26 01:55
I wish

**Comment by lehjr** [comment] 2017-04-26 02:01
Should I ditch the spinning cube? If I get rid of it, I can change to a JSON model and users can override with their own model if they want.

**Comment by eyeonus** [comment] 2017-04-26 02:05
I kind of like the cube. Can you still go JSON if it isn't spinning?

**Comment by eyeonus** [comment] 2017-04-26 02:06
Because if not, go ahead and ditch it.

**Comment by lehjr** [comment] 2017-04-26 02:10
The spinning cube is done in the model renderer which is done in the ModelBase model. The spinning cube isn't easily implemented with JSON models. It's not impossible, but I have no idea how to do it. It's not well documented. The JSON models are a completely different kind of model though. I could just include a second Tinker Table model as an alternative that can be replaced.

**Comment by eyeonus** [comment] 2017-04-26 02:12
How hard is it to render a not-spinning spinning cube in JSON?

**Comment by lehjr** [comment] 2017-04-26 02:14
Rendering a static model ( non-animated ) is easy, to a point. Rotations are kind of limited on the parts though.

**Comment by eyeonus** [comment] 2017-04-26 02:16
Um, I found this thing, which apparently makes it easy to create an animated JSON model and export the JSON code once you're done.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/2715476-block-models-json-model-animator

Maybe, if you want to, you can take a look at it? Unless you /REALLY/ want animations in the model, I wouldn't bother.

**Comment by lehjr** [comment] 2017-04-26 02:21
Well that certainly is Interesting. Hmm. I'll have to see if I use that.

**Comment by eyeonus** [comment] 2017-04-26 02:38
While I'm at it, I also found this video tutorial on making animated JSON models in Minecraft:
https://www.youtube.com/watch?v=HrNWnQO4aeg

**Comment by lehjr** [comment] 2017-04-26 12:52
Thanks. I changed the texture a bit more for now. The model type change will have to wait until after the first beta. For now the issue of rendering glitches should be more or less done and I can focus on the alpha issue list. 

![2017-04-26_08 48 21](https://cloud.githubusercontent.com/assets/1084367/25435193/3c1db56c-2a5d-11e7-85b6-c18bf3c3a485.png)

**Comment by eyeonus** [comment] 2017-04-26 16:06
Looking good.

**Comment by lehjr** [comment] 2017-05-01 11:30
Is this still an issue with the latest beta?

**Comment by eyeonus** [comment] 2017-05-04 03:38
Yes.

I did the same setup as in the OP, it is definitely translucent, although not nearly as noticeable.

![2017-05-03_21 37 16](https://cloud.githubusercontent.com/assets/1733600/25689852/c896ae7c-3048-11e7-9d13-ffd143dfe67f.png)
![2017-05-03_21 37 28](https://cloud.githubusercontent.com/assets/1733600/25689851/c892c050-3048-11e7-9e56-79b1c6031cdd.png)

**Comment by eyeonus** [comment] 2017-05-04 03:39
Nice job with the spinning cube by the way. That's pretty cool.

**Comment by eyeonus** [comment] 2017-05-04 04:19
![2017-05-03_22 17 58](https://cloud.githubusercontent.com/assets/1733600/25690432/7b2a7d16-304e-11e7-8c02-0979c308b445.png)
Here's a better view of it when it's translucent. Interestingly, this only seems to happen when there's a beacon involved now. If I remove the beacon the chest doesn't go translucent.
![2017-05-03_22 19 40](https://cloud.githubusercontent.com/assets/1733600/25690449/a99cc460-304e-11e7-8c79-803f285f8510.png)
![2017-05-03_22 20 17](https://cloud.githubusercontent.com/assets/1733600/25690453/b185ec38-304e-11e7-884f-ebffbf14cd3d.png)

(EDIT: Sorry it took so long for me to get around to testing this, life has been especially hectic lately.)

**Comment by eyeonus** [comment] 2017-05-04 04:24
One more thing: it's not the beacon itself doing it, it's the beacon's beam. Managed to grab this screenshot just before Minecraft started rendering the beacon beam:
![2017-05-03_22 23 20](https://cloud.githubusercontent.com/assets/1733600/25690492/3162ef14-304f-11e7-883c-d2d254635395.png)

**Comment by EzerArch** [comment] 2017-05-04 07:00
> One more thing: it's not the beacon itself doing it, it's the beacon's beam.

Oh, so it's Mojang breaking stuff again? >:(

Could you test to see if there's a max distance triggering the bug? Or even putting them in different chunks. It's not like I/anyone will put a chest and a tinker table near a beacon that close to each other that way. 

I could place the beacon and the other stuff a few blocks/chunks apart and the bug will be never triggered.

**Comment by lehjr** [comment] 2017-05-04 12:19
There really isn't anything more that can be done with this. Rendering post 1.7.10 will always be fragile and buggy for various reasons, such as how multi-threaded rendering is implemented using terribly outdated libraries like lwjgl-legacy. They have confirmed that they will switch to lwjgl3 in the future, but "for a version after 1.12", so probably not for another year or more, if they don't kill it by then.

**Comment by lehjr** [comment] 2018-08-31 03:19
Closing this since nothing can really be done for versions prior to 1.12.2 without porting the new model.

**Closed as completed by lehjr** 2018-08-31 03:19 UTC
