### ISSUE TITLE
No recipes on 1.8.9 version

### ISSUE THREAD

**Issue by JSJBDEV** [MachineMuse/MachineMusePowersuits#714] opened 2016-04-18 18:25 UTC
Me and a friend have a 1.8.9 (private-ish) mod pack and there are no recipes for any of the items in power suits, we tried downloading the recipes from curse forge but build.technicpack appears to not exist, if possible could we have the recipes (or at least a recipe so we can work out how to add recipes using numina)
Version: Alpha3
Thanks

**Comment by lehjr** [comment] 2016-04-18 18:35
I have a version of Numina with JEI support. I haven't had the chance to test it though. I'll upload it in about an hour.

**Comment by JSJBDEV** [comment] 2016-04-18 18:36
Is it a JEI thing? We were wondering that.

**Comment by JSJBDEV** [comment] 2016-04-18 18:38
Thank you very much though :)

**Comment by lehjr** [comment] 2016-04-18 18:40
Just enough items works. I'm not sure of the status of Not enough items, but I believe it's ether dead or in limbo.

**Comment by JSJBDEV** [comment] 2016-04-18 18:41
ah, we have JEI I meant is the resasons there aren't any recipes to do with JEI

**Comment by lehjr** [comment] 2016-04-18 18:44
yes. JEI support has to be added, the NEI plugin was very different and most of it didn't survive.

**Comment by JSJBDEV** [comment] 2016-04-18 18:45
Cool, thanks

**Comment by lehjr** [comment] 2016-04-18 20:47
That should be available now and hopefully working.

**Comment by AgentA1cr** [comment] 2016-04-19 00:01
I'm having a similar issue. I've updated to the latest version of Numina, and it hasn't solved the problem. I checked the config\machinemuse\recipes folder, and it's empty. I also checked all the config files. The only option I could find that seemed to be related was B:"Auto-extract recipes"=false, which I tried setting to true. That hasn't helped either.

**Comment by lehjr** [comment] 2016-04-19 01:11
if you extract the recipes manually it should work. Extraction was disabled during porting, and should be fixed in the next MPS build sometime this week. Numina handles the JEI plugin, but not the recipe extraction.

**Comment by AgentA1cr** [comment] 2016-04-19 02:02
How do I manually extract the recipes?

**Comment by Keltas** [comment] 2016-04-19 10:02
I wanted to ask the same question, but I've dug around the repository a little and found it.Go to "MachineMusePowersuits/src/main/resources/", copy the recipe file you want and put it in recipes folder in config. Vanilla recipes seem to work and are recognised by JEI.

**Comment by JSJBDEV** [comment] 2016-04-19 15:32
thanks @Keltas I'll try that

**Comment by meatloaf4311** [comment] 2016-04-20 01:23
https://github.com/MachineMuse/MachineMusePowersuits/blob/experimental/src/main/resources/mps-vanilla.recipes

**Comment by meatloaf4311** [comment] 2016-04-20 01:25
I just don't know how to make a file of it to put in recipes folder

**Comment by JSJBDEV** [comment] 2016-04-20 14:55
So it appears to work in single player, with vanilla recipes (other types crash) but not multiplayer?

**Comment by lehjr** [comment] 2016-04-21 02:52
Thanks for the feedback. I'm in the process of looking into this.

**Comment by lehjr** [comment] 2016-04-26 16:02
For the issue with this not working in Multiplayer, does anyone with this issue have this in their logs? 
`[11:36:16] [Netty Server IO #3/ERROR]: Failed to read message: java.lang.IndexOutOfBoundsException`

As far as I can tell so far, it seems to be a packet issue. I've found that if I go into JEI, and change the "Item Cheating mode" and exit JEI, then go back in and change it back and exit it does work after. However this is not a solution but a temporary work around (if it works for everyone else) until it is fixed.

**Comment by lehjr** [comment] 2016-04-28 13:27
Looks like the crash with recipes is caused by invalid recipes. Remember, these recipes have not yet been checked, especially the IC2 recipes since there wasn't any version for 1.8.9 in until a few days ago. I'm currently looking working on updating the MPS-IC2 recipes to reflect the internal name changes. Other recipes may also be affected.

**Comment by hydrasbane1** [comment] 2016-04-30 22:57
I have had the same problem, I coped the mps-vanilla.recipes file into .minecraft/config/machinemuse/recipes and I still cant craft anything.

**Comment by lehjr** [comment] 2016-05-01 01:01
I should be uploading a new build of MPS and Numina tomorrow.

**Comment by AgentA1cr** [comment] 2016-05-08 22:12
Most recipes seem to be working now, but the recipe for wiring is still broken. It shows up in jei, but putting the designated ingredients in the crafting table doesn't produce anything. I believe it may be metadata or nbt related. Jei displays the cable as copper, but the metadata indicates gold cable. I've tired both, and neither work. I also noticed that the cable displayed in the recipe has no nbt tags, whereas actual ic2 cable items all have 2 tags.

**Comment by lehjr** [comment] 2016-05-08 22:58
That's for the wiring using the IC2 recipe? I'll look into it tomorrow. Any other ones broken that you know of?

**Comment by AgentA1cr** [comment] 2016-05-08 23:05
Haven't found any others, but I'm playing in survival, so I haven't gotten to a lot of the more expensive components yet. So far I've just been using jei to delete the ingredients and "cheat" in the wiring. I need to go whine to mezz about how daggone long it takes to switch in and out of cheat mode... ;)

**Comment by lehjr** [comment] 2016-05-09 11:54
looks like the EnderIO version of the wiring recipe is also messed up.

**Comment by JSJBDEV** [comment] 2016-05-09 15:26
Is this maybe something to do with ID's no longer existing or the item name not cooperating? it might be possible to make a separate mod that adds the recipes back In by using the names. I may try making one

**Comment by lehjr** [comment] 2016-05-09 15:55
I'll be uploading a new version later today. Basically it was because cables now use nbt data instead of meta data. 
`{ "registryName" : "IC2:itemCable", "meta" : 2 }`
now looks like:
`{ "registryName" : "ic2:cable","nbtString" : "{type:0B, insulation:0B}" }`

where **B** is a byte data type

**Comment by lehjr** [comment] 2016-05-09 16:23
new build should be up soon

**Closed as completed** 2017-03-19 14:23 UTC
