### ISSUE TITLE
Plasma cannon never charges fully

### ISSUE THREAD

**Issue by phanski33** [MachineMuse/MachineMusePowersuits#912] opened 2019-04-06 18:33 UTC
When I hold right click to charge the plasma cannon it always resets to 0 at around 40% on the right side hud. I have full power, both sliders at max. In mid air it doesn't charge at all.

**Comment by phanski33** [comment] 2019-04-06 18:36
I'm running version 1.0.36

**Comment by phanski33** [comment] 2019-04-06 20:00
Now it's working and I have no clue why. Between opening this issue and now the only thing that happened was that my game crashed 4 times and I restarted the server twice. It still is a bit glitchy sometimes but now it mostly charges up properly.

**Comment by phanski33** [comment] 2019-04-07 11:13
After removing and adding mods it's back. Not sure what info I should add

**Comment by arnesacnussem** [comment] 2019-04-09 03:35
What version you're current running?(mod ,forge and java).
Also you need provide a mod list(it should contain in any of a full crash-report).

if you haven't delete anything,you can get archived log from log dir and crash-report from crash-report folder.

But still, it maybe cause by a corrupted save files.

**Comment by NilRovaan** [comment] 2019-04-22 13:46
I have the same problem. I tried to charge Plasma Cannon without other parts of suit and it works. When I wear boots it's worked too, but if I have been jumping plasma charge reset. Same with pants. When I don't move everything is good, if walk then plasma is charge reset. I can make the conclusion that it reset when other part of suit use energy or something like this.

**Comment by lehjr** [comment] 2019-04-22 16:27
Cannot reproduce. Needs much more information.

**Comment by Blank517** [comment] 2019-04-25 22:02
https://streamable.com/q8d29

**Comment by lehjr** [comment] 2019-04-25 22:15
Video only illustrates the problem. It doesn’t give me the means to replicate it, and thereby fix it. So unless someone can actually add the required information, I’m not even going to look into this any further

**Comment by eyeonus** [comment] 2019-04-25 23:00
Any people experiencing an issue, the following are REQUIRED to get any help:

--------
#### Issue Submission Form
ALL fields required!
1. Java version:
2. Minecraft Forge version:
3. Detailed description of the issue:
a. What the issue is:
b. What happens when the issue occurs:
c. What steps need to be taken to reproduce the issue:
d. Anything else relevant to the issue not already covered (for example, if it only occurs on existing saves, but doesn't show up when starting a new game):
4. Mod list (including versions, provided by crash report if game crashed):
a. Smallest sub-list that still produces issue, if any exclusion testing was done:
5. Log files (Link to pastebin, gist, or other hosting site preferred, file attachment okay, do NOT paste directly):
a. Game log (make sure it's the log that was generated during the gameplay the issue occurred in):
b. Crash report (if issue caused game to crash):
c. Server log (if issue occurred on a server, make sure it's the log generated during the gameplay the issue occurred in):
d. Server crash report (if issue caused server to crash):
6. Anything else relevant (such as links to issue reports for other mods when issue is due to mod compatibility issues, for example):

--------

**Comment by Blank517** [comment] 2019-04-26 12:42
**Java**: 1.8.0_201
**Forge**: 1.12.2-14.23.5.2836

**Mods list**:
MachineMuse's Modular Powersuit (1.0.39)
Numina (1.0.36)
Redstone Flux (2.1.0.6)
RFTools (7.61)
McJtyLib (3.1.1)

**Issue**:
The issue trigger when is installed any power generation module on the armor and it charges the Power First.
The issue causes the reset of any action the Power First is doing (charging plasma cannon, breaking a block, ...)
It happens both on the client and on the server.

**Logs**:
There aren't errors related to this problem in [latest.log](https://hastebin.com/qodedejiko.md) or debug.log

**Other**:
In [this video](https://streamable.com/q8d29) I successfully charge the Plasma Cannon without armor  and then I equip the armor with Kinetic Generator and High Efficiency Solar Generator modules but is not possible to charge it anymore.

I apologize if the explanation is not clear but English is not my native language

**Comment by eyeonus** [comment] 2019-04-26 17:34
Accurate issue naming also helps:
~~Plasma cannon never charges fully~~Power generation modules reset any power fist action when generating power

**Comment by lehjr** [comment] 2019-04-26 21:20
Given the new information, this is likely an issue with the NBT data being changed while the item is in use. A bit of searching reveals this is a vanilla issue, but can be fixed by not charging the item while in use. Should be a relatively simple change in the code to fix it.

**Comment by lehjr** [comment] 2019-04-29 00:06
This should be fixed in Numina build 37.

**Closed as completed** 2019-05-02 11:41 UTC
Labels: Can't Reproduce, Interesting, Missing information
