### ISSUE TITLE
Add hard number modification in addition to slider use

### ISSUE THREAD

**Issue by mathwizi2005** [MachineMuse/MachineMusePowersuits#559] opened 2014-12-29 06:21 UTC
This is more of a feature request then an issue but adding editable values in addition to the slider for armor plates and batteries, to name a few, would round out the modification menus.

**Comment by MachineMuse** [comment] 2015-04-27 20:25
it's a good idea but it's not a bug so I'm closing this issue

**Closed by MachineMuse** 2015-04-27 20:25 UTC
