### ISSUE TITLE
[1.16.4] Observations 

### ISSUE THREAD

**Issue by CrossVas** [MachineMuse/MachineMusePowersuits#985] opened 2021-02-04 17:43 UTC
**Version info**
Minecraft version: 1.16.4
Minecraft Forge version: 35.1.28

**Describe the bug**
1. Workbench missing model and localization;
2. Silk touch enchantment module missing texture;
3. Armor is listed upside down in workbench when equipped;
4. Workbench doesn't show you the required materials when you choose a module to install;
5. Recipes are messed up (components can't be crafted), it needs to be polished;
6. Components don't stack;
7. Modules missing options' localization;
8. Salvation button sometimes doesn't work (when you install a module and then try to uninstall it) - tried with amor plates
9. Armor plates have no effect (you can install them, but get 0 armor points)

It is impossible to do some more testing unless these (or at least item stacking) are not fixed

**Mod list**
ftb-gui-library-1604.1.1.26;
jei-1.16.4-7.6.0.57;
ModularPowersuits-1.16.4-2.0.1;
Numina-1.16.4-2.0.1.

**Log files**
[latest.log pastebin](https://paste.ubuntu.com/p/vJX9yvXnZD/)

**Screenshots**

![2021-02-03_22 03 22](https://user-images.githubusercontent.com/25727222/106930339-1988af00-671e-11eb-9a12-4d9ccdd76ef2.png)
![image](https://user-images.githubusercontent.com/25727222/106930504-4b9a1100-671e-11eb-9ed4-09196c0690a4.png)

![image](https://user-images.githubusercontent.com/25727222/106930390-27d6cb00-671e-11eb-9e8a-3e30480226dd.png)
![image](https://user-images.githubusercontent.com/25727222/106930598-68364900-671e-11eb-8dc6-783047470a12.png)
![image](https://user-images.githubusercontent.com/25727222/106930758-90be4300-671e-11eb-95a8-9f5874c4dc49.png)
![image](https://user-images.githubusercontent.com/25727222/106931175-f3afda00-671e-11eb-942b-4505bd1602e6.png)

**Comment by EzerArch** [comment] 2021-02-04 20:36
Wrong repository, please: https://github.com/lehjr/ModularPowerArmor (ping @lehjr )

**Comment by lehjr** [comment] 2021-02-04 20:38
> Wrong repository, please: https://github.com/lehjr/ModularPowerArmor (ping @lehjr )

actually, it's this one: https://github.com/lehjr/MachineMusePowersuits
Since I have access to the Curseforge page again, it's just easier since everyone knows MPS better than MPA.

**Comment by lehjr** [comment] 2021-02-05 16:17
> 1. Workbench missing model and localization;
Not actually missing, just missing proper reference. Already fixed in code. 

> 2. Silk touch enchantment module missing texture;
The silk touch doesn't have an icon yet. I'm still not even sure what that should look like. 

> 3. Armor is listed upside down in workbench when equipped;
That's a sorting issue related to how Minecraft handles it's slots. It's probably not going to get fixed right away. It's annoying but it's not game breaking and I'm looking at replacing parts of the GUI at some point. 

> 4. Workbench doesn't show you the required materials when you choose a module to install;
Install costs were removed after 1.12 due to use of capabilities. Modules are now items and are directly crafted. 

> 5. Recipes are messed up (components can't be crafted), it needs to be polished;
Like other things, recipes are still a work in progress. The biggest issue is that having recipes specifically tailored to other mods like in previous versions only works when those mods are installed. Since the mod doesn't add its own materials, vanilla recipes are pretty limited and "uninspiring". 

> 6. Components don't stack;
Fixed in code, will be in the next alpha.  

> 7. Modules missing options' localization;
Mostly fixed in code. 

> 8. Salvation button sometimes doesn't work (when you install a module and then try to uninstall it) - tried with amor plates
Confirmed. Probably going to take quite a bit of time to fix this. 

> 9. Armor plates have no effect (you can install them, but get 0 armor points)
Fixed in code, will be fixed in next alpha.

**Comment by CrossVas** [comment] 2021-02-05 16:43
@lehjr, could you please open the Issue tab on your fork to post further results there since this repo is not active?

**Comment by lehjr** [comment] 2021-02-05 23:13
> @lehjr, could you please open the Issue tab on your fork to post further results there since this repo is not active?
The repo accepts issues now. I'll probably have a few more to add.

**Comment by CrossVas** [comment] 2021-02-06 10:23
@lehjr what do you think about these one for fortune and silk modules? 
[modules.zip](https://github.com/MachineMuse/MachineMusePowersuits/files/5936625/modules.zip)

![image](https://user-images.githubusercontent.com/25727222/107115509-d3defa00-6875-11eb-9707-0db40376260b.png)

![image](https://user-images.githubusercontent.com/25727222/107115516-de00f880-6875-11eb-8364-bec0c7ada589.png)

**Comment by lehjr** [comment] 2021-02-06 23:13
> @lehjr what do you think about these one for fortune and silk modules?
Looks good to me.

**Comment by Crimsonhime327** [comment] 2021-02-07 22:37
![image](https://user-images.githubusercontent.com/78706711/107161476-58fc0900-6973-11eb-99f4-703ca8992ecf.png)
![image](https://user-images.githubusercontent.com/78706711/107161503-79c45e80-6973-11eb-8344-6aa5495768a3.png)

there is missin texture or something on the power gauntlet. and i can't install some upgrades no matter how many times i try

**Comment by Crimsonhime327** [comment] 2021-02-07 22:38
![image](https://user-images.githubusercontent.com/78706711/107161532-a24c5880-6973-11eb-9b4e-2f71a11880b9.png)
i can't install binoculars and night vision

**Comment by Crimsonhime327** [comment] 2021-02-07 22:39
how we're supossed to charge the batteries anyway?

**Comment by Crimsonhime327** [comment] 2021-02-07 22:41
![image](https://user-images.githubusercontent.com/78706711/107161590-096a0d00-6974-11eb-8542-8ccaf2686409.png)
i can't install those upgrades

**Comment by lehjr** [comment] 2021-02-07 22:41
> how we're supossed to charge the batteries anyway?

Charge pad from numina or energy generator. There really isn't much in the mod as far as energy generation, solar generators, thermal, and kinetic.

**Comment by lehjr** [comment] 2021-02-07 22:43
Unlike previous versions of the mod, there is a limit as to what can be installed. For instance, only one energy storage device can be stored in any single piece of armor. The GUI needs to be updated to reflect this, but that's a bit far down on the list of priorities

**Comment by CrossVas** [comment] 2021-02-07 23:34
I guess this issue can be closed as now we have issue tab on your fork, @lehjr, right?

UPD: Further info/discussion could be done/written there.

**Closed as completed** 2021-07-04 20:15 UTC
