### ISSUE TITLE
Nearly all recipes wrong [SOLVED!]

### ISSUE THREAD

**Issue by rike456** [MachineMuse/MachineMusePowersuits#676] opened 2015-12-29 16:06 UTC
I've got the latest version of IC2 and Thermal Expansion and the recipes won't work. Could i get an download for all the recipes etc to fix this?

**Comment by rike456** [comment] 2015-12-29 16:08
I cant find those recipes not on any website neither.

**Comment by lehjr** [comment] 2015-12-29 16:11
First, make sure you are using the latest version of Numina, the version from Curseforge, not Curse.
Second, the recipes are already in the jar file. However, I'm pretty sure that new recipes won't extract over old ones, this is intended behavior as this would overwrite custom recipes. Also, make sure you have at least build 283 of MPS.

**Comment by rike456** [comment] 2015-12-29 18:12
I'll try this then +1:

**Comment by rike456** [comment] 2015-12-29 18:32
Now my server says that i dont have Numina -0.4.0.131.jar but i got it.

**Comment by rike456** [comment] 2015-12-29 18:41
The problem was the Numina. I downloaded it before on Curse, not Curseforge. Thank you for your help :)

**Comment by EzerArch** [comment] 2015-12-29 21:32
If solved, please close the issue.

**Closed as completed** 2015-12-30 00:37 UTC
