### ISSUE TITLE
Numina is sending 20 packets a second at 5 KB/s 

### ISSUE THREAD

**Issue by ajthemacboy** [MachineMuse/MachineMusePowersuits#699] opened 2016-01-26 13:27 UTC
I run a modded server with Numina and PowerSuits installed. When running OPIS to diagnose what's using up all the network bandwidth I found that Numina is sending a ton of packets, very fast.

Here's a screenshot: http://i.imgur.com/ZUrf841.png

I'm wearing a PowerSuit, and the packets stop when I put the PowerSuit in a chest. (If I simply take it off and leave it in my inventory, nothing changes.)

The PowerSuit only has Diamond Plating, Shock Absorbers, Energy Sheilds, and HV batteries installed. The packets are sent when I am just standing still. 

There is absolutely no reason these packets should be sent this frequently and they should be no where near as large as they are. There are no config options to adjust packets.

**Comment by lehjr** [comment] 2016-01-26 16:29
Unfortunately, I'm not familiar with the packet code in MPS but there sure seems to be a lot it (one thing to look at it, another to understand it all). Actually, it looks like there's a packet for everything: https://github.com/MachineMuse/MachineMusePowersuits/blob/experimental/src/main/scala/net/machinemuse/powersuits/network/packets/MPSPacketList.scala

**Comment by ajthemacboy** [comment] 2016-01-26 17:13
@lehjr I'm no dev but that's certainly a lot... NONE of those, even all of the combined, shouldn't be sent twenty times a second though.

**Comment by lehjr** [comment] 2016-01-26 17:47
It's probably once per tick

**Comment by flowtender** [comment] 2016-01-27 21:15
It is indeed once per tick (per player) and there are several reasons why. But judging by your tone I gather you don't care about the reason and are just angry for no reason so I'm just going to close this.

**Closed as completed** 2016-01-27 21:17 UTC

**Comment by ajthemacboy** [comment] 2016-01-27 22:20
I'm angry for 'no reason' because your mod is using a ton of bandwidth on my server. I'm not creating drama just for attention. I'm almost positive there are ways to check player location or whatever it is these packets are for without sending updates once per tick. Forge has APIs for this stuff after all.

**Comment by ghost** [comment] 2016-01-27 22:33
Hmm, why exactly was this closed? It seems like a pretty significant bug to me.

**Comment by flowtender** [comment] 2016-01-27 23:24
It is not a bug. It is a requirement for the advanced movement options which are the original use case for MPS. If your server cannot handle 5 kb/s per player then you do not meet the minimum system requirements to run MPS. Even a 56k dial-up modem can handle this amount of traffic for one player.

"I am not a dev but this is unacceptable" might be an appropriate response if I had advertised lower bandwidth consumption and you had paid real live money for the product. Since none of those things are the case, check your attitude.

**Comment by ajthemacboy** [comment] 2016-01-27 23:34
What specific part of the mod requires so many packets..? Jetpacks? Gliders?

**Comment by flowtender** [comment] 2016-01-27 23:36
It is a requirement for the advanced movement options

**Comment by ajthemacboy** [comment] 2016-01-27 23:37
Yes, but what specific part? That's ambiguous.

**Comment by flowtender** [comment] 2016-01-27 23:37
No, it isn't.

**Comment by ajthemacboy** [comment] 2016-01-27 23:38
"Advanced movement options" IS ambiguous. Do you mean the options for a JETPACK? A GLIDER?

**Comment by flowtender** [comment] 2016-01-27 23:39
All of them. If it changes anything about how the player moves from their vanilla capabilities, including how fast, then it needs to notify the server so that it doesn't kick them for moving too fast or floating too long or something like that, and so that fall damage is still calculated correctly.

**Comment by ajthemacboy** [comment] 2016-01-27 23:44
Jetpack: Mekanism, IndustrialCraft, Simply Jetpacks, and more all create jetpacks without this much bandwidth and these many packets.

Glider: OpenBlocks and Ender IO both have gliders that don't use this much bandwidth or this many packets. 

Technically Archimede's Ships [Plus] creates moving and flying entities, sometimes massive, without this much bandwidth or this many packets.

Minecraft itself, RailCraft, Refined Relocation, Steve's Carts, and more create Minecarts that can move in all kinds of ways without this much bandwidth or this many packets.

Pistronics creates massive rotating and moving pistons without this much bandwidth and this many packets.

Every mod that adds frames, RedPower, ProjectRED, BluePower, Framez, etc, create tons of moving blocks and moving entities without this much bandwidth or packets. 

Some of these examples might not be applicable, but your mod DOES NOT NEED to use THIS MUCH BANDWIDTH. There are BETTER WAYS TO DO THIS. (Sorry for the caps.) 

Seriously, **no other mod** on my server with 10 players online uses this much bandwidth. Yours uses about 5 times more than any other mod, with players using jetpacks and all kinds of machines.

Edit: Oh and Portal Gun projects and throws entities reallllly fast without this much bandwidth.

edit 2: Iron Man as well.

**Comment by flowtender** [comment] 2016-01-27 23:47
Then use those mods instead if bandwidth is more of a concern than fidelity.

**Comment by ajthemacboy** [comment] 2016-01-27 23:48
I love your mod, it's amazing, I don't want to use those mods and neither do most of my players. The problem is that it's not optimized and I'm trying to tell you about a bug so you can IMPROVE your mod! 

Why is that such a big deal? You act like I'm attacking you or something >_>

**Comment by flowtender** [comment] 2016-01-28 00:02
You are attacking, though. You're saying 'There is absolutely no reason why it should be this way', as if I couldn't possibly have thought about it and made a decision. But I didn't design to your requirements, I designed to mine. Yes, MPS uses a 'lot' of bandwidth (compared to other Minecraft mods, but not compared to other games).
- MPS is also the only mod that accurately calculates fall damage based on impact velocity as a server-side calculation. That alone was reason enough for me to design it that way.
- MPS is also the only mod that scales energy consumption based on precise movement instead of a simple on/off switch (this hasn't always worked because of changes to vanilla's movement/network handling but it has been designed to at least.)
- MPS is (as far as I know) the only mod that changes how high you jump based on how long you hold down the button. (except Smart Moving which does it based on how long you hold down the button _prior_ to jumping, instead of having an instantaneous effect, which completely changes how it feels)
- MPS permits some form of controlled flight that isn't simply enabling Creative Mode flight or allowing jumping in midair. (Maybe simply jetpacks goes beyond this, not sure, haven't used them) This code is also used for the underwater jet module.
- MPS keeps most of the server-side movement sanitization intact, so that e.g. players who are using hacked clients will still have to build a jetpack if they want to avoid getting kicked for floating.

These features are part of what set MPS apart in the first place, and all of them require constant velocity & position updates or else you end up e.g. taking fall damage based on how fast you were going half a second ago.

I'm not changing it and this isn't open for debate. I'm not sure why I bothered to explain it at all when you clearly don't want to hear it. I guess for the others reading this.

And don't use that word 'optimized' until you _really_ know what it means.

**Comment by flowtender** [comment] 2016-01-28 00:15
For an example of another game which is _very_ "well-optimized", designed by people much more experienced and knowledgeable than me,
https://developer.valvesoftware.com/wiki/Source_Multiplayer_Networking

**Comment by ajthemacboy** [comment] 2016-01-28 15:14
I suppose asking you to add a config option to disable these calculations and updates would be out of the question, since you're so incredibly stubborn. (Now I'm attacking.)  Most other mods get away without these 'accurate calculations' and I've never even noticed, I'm pretty sure MPS doesn't need to be the exception.

**Comment by eyeonus** [comment] 2016-01-28 15:59
I know of no other mod with configurable superspeed.

**Comment by flowtender** [comment] 2016-01-28 19:24
This isn't me being stubborn, this is me being patient enough to tell you why it is the way it is. I hate to say this but you are really not qualified to be telling anyone what their code should do.

Besides, I don't have time or energy to make any comprehensive changes. If you want to fork MPS, 'fix' the bandwidth 'issue', and make a pull request, I promise I'll give it a fair evaluation.
