### ISSUE TITLE
keybinds set in gui don't save across client restarts

### ISSUE THREAD

**Issue by willis936** [MachineMuse/MachineMusePowersuits#636] opened 2015-11-01 00:48 UTC
Only tested in SMP.

**Comment by flowtender** [comment] 2015-11-21 01:56
Are they keybinds that are taken by other keys? Do you have read/write access to your config folder?

**Comment by willis936** [comment] 2015-11-21 03:36
There are overlap on keybinds for MPS but none that are set in the gui.

Also no files are marked read only and all users have all permissions to the folder.

**Comment by EzerArch** [comment] 2015-11-23 03:54
What I can confirm:
* The position of module icons changes every game reload, sometimes pretty messed up. Probably sizing the game window affects it.
* Once reloaded, the game doesn't load all HUD icons and the keybinds, so you have to open the Tinker Table's keybinder to make the game "remember" them.
* Sometimes some keybind hooks are lost. It seems it stopped after I deleted the powersuits-keybinds.cfg and let the game recreate it.

**Before game reload**
1. My options.txt: https://gist.github.com/EzerArch/3122e0fccdda85ad0156
2. My powersuits-keybinds.cfg: https://gist.github.com/EzerArch/1208c10bd798af7adae1
3. In-game screenshots:
![2015-11-23_01 12 20](https://cloud.githubusercontent.com/assets/6743303/11329162/544f5082-917f-11e5-876f-21bdc719af97.png)
![2015-11-23_01 12 31](https://cloud.githubusercontent.com/assets/6743303/11329163/54518dac-917f-11e5-9978-33fe21d27d74.png)

**After game reload**
1. My options.txt: same
2. My powersuits-keybinds.cfg: https://gist.github.com/EzerArch/bf7f26ef507f4c87aad2
3. In-game screenshots: 
![2015-11-23_01 17 02](https://cloud.githubusercontent.com/assets/6743303/11329399/b5fa3d44-9182-11e5-8145-fa7a2a4b8292.png)
![2015-11-23_01 40 16](https://cloud.githubusercontent.com/assets/6743303/11329436/42ea2cdc-9183-11e5-8087-5f3fe8a58bb8.png)

There is a something else I think is worth pointing out: you can set a keybind for "Zoom (MPS)" on game controls (default "Y", I've never got it to work) and a keybind for Binoculars at the TInker Table's keybind window. I'd remove the "Zoom (MPS)" from game controls to free up a key.

**Comment by flowtender** [comment] 2015-11-25 01:28
Good point; can you make another ticket to remove the zoom keybind? thanks :)

**Comment by Keridos** [comment] 2015-12-11 13:06
For me the reset of keybinds happens when I use F as well, somehow it still is selected in the keybind gui but I need to open the GUI once on client restart for it to actually be registered.

**Comment by audiogarden21** [comment] 2016-12-10 23:42
From what I can tell the mod has issues with conflicting keybinds. I just deleted my keybinds config file, set my keybinds, then reloaded the game entirely and the only keybinds that stuck were three that had no conflicts.

I use J, B, F, X, N, and Tilde/Grave for Jump Assist, Jet Pack, Sprint Assist, Step Assist, Night Vision, and Flight Control respectively. Prior to doing all of this I removed the conflicts on B, and the only one that stuck prior was J which had no conflicts. Tilde/Grave wasn't being used since I just installed the Jet Pack and assigned it to B just before attempting to do anything.

The only keybinds that stuck were J, B, and Tilde/Grave since they had no conflicts with other keybinds.

EDIT

I should note that "conflicting" doesn't mean a keybind has to have conflicts with other keybinds, but rather if any key - that is being used for MPS keybinds - is being used for any other purpose in the game then it will not save. In other words, if a keybind says "Taken" when you create a new one, then it won't save.

After going through all of the keybinds in Minecraft Controls and removing all the ones mentioned in my post and reloading the game, all the keybinds are there in the Tinker Table and functioning as they should.

**Comment by audiogarden21** [comment] 2016-12-13 02:40
J and B are no longer saving even though they were both saving initially, and are still not taken.

I'm not sure what's up with that but it's still better than having to reset every hotkey any time I load up my save.

**Comment by lehjr** [comment] 2017-03-27 14:44
So far I can't reproduce in 1.10.2. If this happens again there we can reopen this issue. 1.7.10 is no longer supported.

**Closed by lehjr** 2017-03-27 14:44 UTC
Labels: bug

**Comment by MaverickMartyn** [comment] 2020-08-22 13:50
Fairly sure I'm having this issue. I'm running a customized FTB Revelation pack.
After each restart, I have to go to the Tinkers Table, and open the keybinds UI, in order for it to load my keybinds.
They don't even show up on the HUD either, until I do that.
The only keyind I currently have is Flight Control, which I have mapped to the Home key.
As far as I can tell, it serves no other purpose in my game.
