### ISSUE TITLE
Crash After updating Nuclearcraft

### ISSUE THREAD

**Issue by BedrockLegends** [MachineMuse/MachineMusePowersuits#941] opened 2019-07-17 15:22 UTC
**Version info**
Java version: 221
Minecraft Forge version: 1.12.2

**Describe the bug**
Launch Pack and boom crash 
https://paste.dimdev.org/ayadewagoz.mccrash
**To Reproduce**

**Expected behavior**

**Mod list**
Including versions, provided by crash report if game crashed:
https://paste.dimdev.org/ayadewagoz.mccrash
Smallest sub-list that still produces issue, if any exclusion testing was done:

**Log files**
(Link to pastebin, gist, or other hosting site preferred, file attachment okay.)
Game log (make sure it's the log that was generated during the gameplay the issue occurred in):
Crash report (if issue caused game to crash):
Server log (if issue occurred on a server, make sure it's the log generated during the gameplay the issue occurred in):
Server crash report (if issue caused server to crash):
https://paste.dimdev.org/ayadewagoz.mccrash
**Screenshots**

**Additional context**

**Comment by lehjr** [comment] 2019-07-17 16:28
Duplicate of #940

**Closed as completed by lehjr** 2019-07-17 16:28 UTC
