### ISSUE TITLE
RailGun

### ISSUE THREAD

**Issue by HideAwayDk** [MachineMuse/MachineMusePowersuits#847] opened 2018-08-31 22:10 UTC
Hey :)
I find the rail-gun a little wridet ? sometimes it works when i shot a zombie fx, but most time its just like the shot go right through em and they don't take any damage ? is this a knowen bug or ? :)

**Comment by dash16** [comment] 2018-08-31 22:33
I’m seeing this too.  I’ve tried tweaking power output on the railgun and it doesn’t seem to help. Just randomly maybe one in 20 shots seem to actually connect and do damage.

**Comment by lehjr** [comment] 2018-08-31 23:08
Just tested it and wasn't even able to damage a sheep at close range.

**Comment by HideAwayDk** [comment] 2018-08-31 23:10
Well its maybe animal friendly :D

**Comment by lehjr** [comment] 2018-08-31 23:14
I'll look into it this weekend. I'm currently working the ore scanner module, switching over to use the setup from Scannable. After that's finished I'll see what I can do.

**Comment by HideAwayDk** [comment] 2018-08-31 23:18
Thanks :) 👍 Anyway have you made some documentation on how the new "weight" system works ? i'am having a bit trouble on how to figure it out, you know Armor slots vs not taking damage from falling fx and armor plate/energy shield vs not taking damage from mobs, and so on

**Comment by lehjr** [comment] 2018-08-31 23:24
The weight mechanic is being replaced with a point based system where each item has so many points available to settings and installing modules. This was done because the weight mechanic can be circumvented and it really doesn't fit in with Minecraft, especially when you can store a mountain in your inventory with no penalty. All of the modules will likely need some level of tweaking in the settings. Keep in mind, this is still early in the Alpha phase.

**Comment by HideAwayDk** [comment] 2018-08-31 23:25
I do understand lehjr :) just trying to make a good balance :)

**Comment by lehjr** [comment] 2018-09-01 00:00
using a point based system has an advantage over the weight mechanic. The weight mechanic gets constantly checked and then applied to a movement limiter. The point based system only needs to be looked up when the Tinker table GUI is open and is applied individually for each item (even though the current display shows all of the points being used. That's actually just a leftover from the weight mechanic).

**Comment by lehjr** [comment] 2018-09-03 17:38
Railgun issue is caused by an issue in the Entity ray trace code in MPS. It's supposed to figure out if the player is looking at a block, an entity, or nothing. The block code is pretty easy, but the entity code is currently broken. https://github.com/MachineMuse/MachineMusePowersuits/blob/1.12.2-experimental/src/main/java/net/machinemuse/powersuits/utils/MusePlayerUtils.java#L40

The box to scan should be a box around the area to scan, and should change depending on the player's position and where the player is facing. While it does currently change position depending on player position, it does not currently do so depending on the direction the player is facing.

**Comment by lehjr** [comment] 2018-09-03 19:22
This will be fixed in the next alpha

**Closed as completed by lehjr** 2018-09-03 19:22 UTC
Labels: Important, verified
