### ISSUE TITLE
Compiled list of issues found in "ModularPowersuits-0.11.1.107"

### ISSUE THREAD

**Issue by audiogarden21** [MachineMuse/MachineMusePowersuits#742] opened 2016-12-07 19:39 UTC
I'm using the latest updates for this mod in an otherwise normal edition of Direwolf20's 1.7.10 modpack in an SSP world.

**Helm**

_High Efficiency Solar Generator_ - pulses a tick roughly every four seconds that interrupts sliding actions in the GUI station for the mod. Also causes the names of any hotbar-equipped armor piece or power fist (correction - any item) to flash the name of whatever item is selected during these ticks.

Strangely, does not affect my SSP world for some reason, but did affect the test world I created specifically for testing.

Okay, so it appears this only happens when in direct sunlight. When I was in my cave-house it stopped the pulsing. Rain also affects the pulse since it's obviously not considered direct sunlight.

_Compass_ - contains a typo at the end of the description that seems to be related to the lightning attack module.

**Chest**

_Jetpack_ - sound stutters when rate of ascent hits a certain threshold. Generally above 100 joules.

**Legs**

No longer displays knockback resistance in the item tooltip after equipping the Sprint Assist module and only displays the speed bonus. My guess is this is but a simple display issue and has no actual effect on the stats but thought I'd mention it anyway.

**Boots**

None found

**Power Fist**

_Lux Capacitor_ - no longer displays the blue lighting on the entity itself and appears jet black. The light still functions as you'd expect, however.

The image below is what I remember the Lux Capacitor looking like back when I played Tekkit.
https://i.ytimg.com/vi/4M7tS3BwyDU/maxresdefault.jpg

This might just be Sphax, but I'm not entirely sure. Some input would be nice here.

_Shears_ - speed bonus has no effect, otherwise shears as normal.

_Dimensional Tear_ - teleported me from the Overworld to the spawn point in the Overworld with massive heat levels. This particular module I'm not entirely familiar with. I don't believe it was available the last time I played Tekkit years ago, so any input on the behavior of this module would be appreciated.

_Prototype OmniWrench_ - does not tear down Ender IO blocks with shift-right clicks. Appears to work on most of the other mods as expected.

_Chisel_ - currently displays as "module.chisel.name" and appears to do nothing. I'm not entirely sure how the behavior of this module should work so again, any input would be appreciated.

_Lightning Summoner_ - description reads "module.lightningSummoner.desc".

**General**

The slider settings for Sprint Assist are slightly off compared to the previous versions. Before I could get an even 150% walk speed and 200% sprint speed bonus. Now the closest I can get are 149.85 or 150.15 and 199.69 or 200.31, respectively. There's obviously some rogue rounding going on now.

Might I recommend rounding all sliders to the nearest tenth instead of hundredth for simplicity's sake.

**End**

Those are the issues I've discovered thus far. I hope that helps and feel free to inquire for more details if anything is unclear.

EDIT

Could I also inquire as to why there's no longer the torch placer on the Power Fist. That was one of my favorite QoL features of the mod.

**Comment by lehjr** [comment] 2016-12-08 14:10
Thanks for taking the time to test things. Overall, the mod breaking stuff I do have to fix before I can go back to porting the mod to 1.10.2 and above, especially since those bugs would be carried over. However, some of the weird little glitches and things that won't make it to new ports I won't be able to devote any time to. I'm already falling way behind where I need to be. I took a gamble on porting the mod from Scala to Java to make it easier to maintain and port to future versions of Minecraft, but in doing so, I introduced some bugs that are costing valuable time on top of the time spent.

The thing about modpacks is that I don't use them, so I'm not familiar with what mods or settings are in each one, let alone what versions of the mods are in there. In fact, I rarely actually get the time to play as my free time has gone into bug fixing and porting. 

The solar generator issue is pretty much like all power issues. Wireless charging has the same effect. I'm not sure it's something that can be fixed. 

The jetpack sound stuttering has always been an issue. I believe it's a Minecraft limitation.  That's something that probably won't get fixed in 1.7.10. After 1.7.10, sounds are event driven, so that might be solved there. 

The shears I'm not sure about. I the code is in place and running for the speed changing, but I haven't had time to look into it. I'm not even sure how useful a speed setting is for shears. It's something that will have to be looked into later on. 

The OmniWrench is an oddity. It's basically a stripped down copy of the wrench from RedStone Arsenal. It is something that I would take the time to fix later, however, it may not survive beyond 1.7.10 as it relies on CoFH Core and CoFH lib, both of which will probably not be seen in future versions of Minecraft.

The dimensional tear generator works pretty much as intended. It's supposed to return you to whatever your spawn point is when you die. The heat seems to be overkill though, especially when there are alternative options that have no penalty. 

The chisel module, I have no idea. As far as I can tell, it looks like it's something used to harvest blocks, but I don't really know what makes it different from the pickaxe module. 

The compass description is an old and forgotten bug that occurred when I merged the addons into the mod.

**Comment by audiogarden21** [comment] 2016-12-08 17:39
Well quite honestly most of them aren't much of an issue but I would be remiss if I didn't at least mention them so you had a convenient list. However I should also mention that the regular solar panel doesn't cause the same issue that the High Efficiency version does. It's a strange bug that seems to be related to certain installed modules as the effect was intermittent between my test world and SSP world.

In any case, whatever fixes you have in store will probably suffice for me, as I'm not having any major issues that would warrant any real time devoted, however it would be really nice to have the Torch Placer back in action. I miss that thing. 

Thanks for the support you've given this awesome mod. I know how much time can be sucked away from you. I have a handful of mods for Skyrim and Fallout 4, so I know how time consuming it can be.

**Comment by lehjr** [comment] 2016-12-08 17:47
The biggest issue for 1.7.10 is this: https://github.com/MachineMuse/MachineMusePowersuits/issues/738
It's a game breaking issue that I have yet to find the source of and it's preventing me from finishing the 1.10.2 port.

**Comment by audiogarden21** [comment] 2016-12-08 17:53
Yeah, that's quite a puzzling problem they're reporting because it works fine for me in SSP, and I'm using a total of 160 mods in this modpack I'm using so you'd think any issue would crop up in that.

I'm also using Numina .103, which is the one you recommended.

I did however run into some strange bugs when I was adding components in Creative/Cheat mode. Logging out and back in seemed to correct them. I can't recall the exact details but one thing I do recall is that there were three zeros on the right side of the screen next to the power level and the heat level never ticked up at all.

Though I just realized.. Back when I first started updating the mod I ran into some issues in my SSP world when updating to the latest versions of Numina and MPS. I basically performed a clean install of the mod by removing the mods from the mod folder, loading into my SSP world to clear out any references to the mod - similar to clean saving in Skyrim/Fallout 4 mod updates to remove old data - then I logged out and put the updated versions back into the mod folder and everything seemed to work fine after that. Perhaps that's what these guys need to do, because for the life of me I can't see why else they would have a problem while I do not.

**Comment by audiogarden21** [comment] 2016-12-09 00:26
Just wanted to report that keybinds sometimes reset themselves after reloading.

**Comment by EzerArch** [comment] 2016-12-10 17:28
> Just wanted to report that keybinds sometimes reset themselves after reloading.

Probably related to: #636

**Comment by audiogarden21** [comment] 2016-12-10 23:24
The only keybind so far that sticks is J which I use for Jump Assist.

**Comment by Desempregago** [comment] 2017-03-27 09:47
I'm also suffering the jetpack sound stutter in latest 1.10 as well (Alpha 009)

**Comment by lehjr** [comment] 2017-03-27 11:05
the stuttering jetpack sound is actually an easy fix. I meant to put it in the last 1.7.10 build

**Comment by lehjr** [comment] 2017-03-27 13:02
OK stuttering sound is fixed in ModularPowersuits-1.7.10-0.11.1.113. There will be no further 1.7.10 updates.

**Closed as completed by lehjr** 2017-03-27 13:02 UTC
