### ISSUE TITLE
Component meters no longer have any effect (0.11.1.104-Java-Port)

### ISSUE THREAD

**Issue by Stalkstalks** [MachineMuse/MachineMusePowersuits#738] opened 2016-12-02 17:58 UTC
I just installed the newest release from curseforge, and found that the components with adjustable effects (size of batter, zoom level, etc) no longer seem to respect their settings - the battery remains at it's minimum capacity, for example, regardless of what the meter is set to.

**Comment by lehjr** [comment] 2016-12-02 18:24
Interesting. Do you have any log errors? You might see a bunch of log spam when you adjust the sliders.

**Comment by lehjr** [comment] 2016-12-02 18:40
OK, I think the problem was iNumina. Going to upload a new version in a few minutes.

**Comment by lehjr** [comment] 2016-12-02 18:45
Please try with "Numina-0.4.1.103-Java-Port". File should be available as soon as it is "approved" by CurseForge.

**Comment by Stalkstalks** [comment] 2016-12-02 20:13
It seems partially but not completely fixed.

The screen with the sliders still reports the minimum values, and the text output for the battery storage still reports the minimum limit... however, it seems that the battery is charged to the appropriate level, and a plasma cannon seems to actually reflect the settings when used.

(That is, for the plasma cannon, the tinker screen reports the minimum values, but when fired, max charge plasma damage does actually go up to what it should be when the damage is maxed, and turning up the explosion effect does result in explosions when the plasma balls land.)

**Comment by lehjr** [comment] 2016-12-02 21:05
I can confirm the issue after testing in a dev environment. I'll have to dig into it this weekend.

**Comment by lehjr** [comment] 2016-12-02 23:43
New build of MPS should be up soon.

**Comment by Stalkstalks** [comment] 2016-12-03 20:40
Meter settings still don't seem to affect the text on the tinker screen or elsewhere.

**Comment by lehjr** [comment] 2016-12-07 17:06
OK, I was able to reproduce this on a server. However, due to the amount of time it takes for the server to load, this may take some time to track down and fix.

**Comment by navaroneee** [comment] 2016-12-07 19:19
Ok, congrats for the project, I will wait for an resolution
tnks again

*I tried the newst versions of both

**Comment by lehjr** [comment] 2016-12-08 18:16
I can verify that the settings do in fact have an effect on the item itself (using minetweaker) and the data is being set (debugging the packets on the client and server). However, those same settings do not show in the Tinker Table and in the graphical meters. I'm not entirely sure what's going on here.

**Comment by Stalkstalks** [comment] 2016-12-08 20:11
Yeah, it's odd. The client is obviously sending the packets to the server, and the server respecting them when they are used to affect the world.

Is it possible that the GUI numbers are pulling from a copy of the data that is separate from the ones being used for the actual effects? Something like the string/double maps in ModuleTweakFrame not being updated when the data is changed?

**Comment by navaroneee** [comment] 2016-12-09 14:06
I also verified that it works offline only if it does not enter the server first, after entering the server, it stops working offline as well, but it is not only the graph that does not appear, the jetpack, armor and the rest does not work

Again, sorry for my english, I'm Brazilian

**Comment by lehjr** [comment] 2016-12-09 16:06
Hopefully I'll have this figured out in the next couple days. This is the branch I'm working with to track down the source of the problem: https://github.com/MachineMuse/MachineMusePowersuits/tree/1.7.10-Java-Fix

**Comment by navaroneee** [comment] 2016-12-10 19:09
I'm sure you'll solve the problem, if you need me to test, I can help you, thank you.

**Comment by Aeyos** [comment] 2016-12-13 02:34
Anyone knows when this bug was first introduced? It might help tracking down the cause and find a possible solution. I also make myself at your disposal to test and help track down this issue.

**Comment by lehjr** [comment] 2016-12-14 02:05
The source of the issue is somewhere in here: https://github.com/MachineMuse/MachineMusePowersuits/blob/1.7.10-Java/src/main/java/net/machinemuse/powersuits/network/packets/MusePacketPropertyModifierConfig.java

**Comment by lehjr** [comment] 2016-12-14 13:50
found it: https://github.com/MachineMuse/MachineMusePowersuits/blob/1.7.10-Java/src/main/java/net/machinemuse/powersuits/network/packets/MusePacketPropertyModifierConfig.java#L57-L58

**Comment by navaroneee** [comment] 2016-12-14 17:30
lehjr, i found another problem, Numina crash NEI when press U to see the "things to do" with the item

**Comment by lehjr** [comment] 2016-12-14 17:43
The original issue will be fixed in the next release. Any other issues may or may not be in that release as I did some code cleanup while working on the issue. 

Edit: Either way, this will be the last week for any major 1.7.10 work. I can't work on future ports if I'm devoting all of my time on 1.7.10. There just isn't enough time in the day to make that happen with a team of 1. 

Edit 2:
Posting about a crash without any type of crashlog won't help it get fixed.

**Comment by lehjr** [comment] 2016-12-15 13:18
New builds should be up soon. They are labeled as alpha because of internal changes and need testing before being used in worlds people want to keep.

**Comment by navaroneee** [comment] 2016-12-18 19:40
I test 108 and works fine with numina 4, the issue on numina (crash when press U on NEI) is gone too, tnks for your time

**Comment by Stalkstalks** [comment] 2017-01-10 17:45
I just want to say that this looks like it's fixed in the new builds.

**Comment by navaroneee** [comment] 2017-01-25 04:51
lehjr, It seems that the armor when used, does not lose energy under the 40k, as if it were infinite, I tested with the 108 and 109, numina 104
No error log is created

EDIT: Offline works fine, only on dedicated server

**Comment by lehjr** [comment] 2017-01-25 14:57
@RenanVieira88 
1. please create a separate issue ticket for unrelated issues.
2. I probably won't be able to fix it anytime soon. Every hour I spend on 1.7.10 is days lost on 1.10.2 and above. It's unfortunate, but that's the reality of things. The more you have to drop what you are doing, the harder it is to pick up where you left off, that and there are only so many hours in a day.

**Comment by navaroneee** [comment] 2017-01-25 16:18
1. Sorry for posting wrong
2 I understand that you will waste time corringing errors of old versions, I really like your mod, and would like to be able to use it, but I understand your side, thanks for your time

**Comment by lehjr** [comment] 2017-03-27 15:43
Should no longer be an issue. If it returns in 1.10.2 we can revisit.

**Closed as completed by lehjr** 2017-03-27 15:43 UTC
Labels: bug
