### ISSUE TITLE
Crash after adjusting sprint assist

### ISSUE THREAD

**Issue by 1skandar** [MachineMuse/MachineMusePowersuits#862] opened 2018-10-11 17:18 UTC
Apparently turning the assist back down to 0 generates this crash every time you move until the assist is removed entirely :
http://www.vaevictus.net/modular_crashy.txt

**Comment by lehjr** [comment] 2018-10-11 17:31
Information not complete

**Comment by 1skandar** [comment] 2018-10-11 17:51
Sorry, I am working on what has been reported to me. Apparently, he set the sprint to 200%, turned it down to 21% and then down to 0%. And when he tried to walk after that it crashed. And it kept crashing every time he moved until he removed the sprint assist entirely.

**Comment by lehjr** [comment] 2018-10-11 18:27
Still not enough information. I can only assume you are reporting the issue for 1.12.2, but beyond that, there's no version information for the mod or the list of mods being used or for Forge. The problem is that sometimes, it's an interaction issue, sometimes it's changes in Forge. Sometimes the issue has already been fixed but hasn't yet been released. That's why version info is important.

**Comment by 1skandar** [comment] 2018-10-11 18:34
Sorry. latest version of Powersuits (alpha 11) and it's from the modpack Modular Mayhem Reloaded, both from Curse if you want to see a mod list.

**Comment by lehjr** [comment] 2018-10-11 19:00
Yeah, I see the issue. It will be fixed in the next alpha.

**Comment by lehjr** [comment] 2018-10-13 22:23
Fix released.

**Closed as completed by lehjr** 2018-10-13 22:23 UTC
Labels: Missing information
