### ISSUE TITLE
Kinetic Generator module discharge and recharge Wireless Crafting Grid

### ISSUE THREAD

**Issue by Blank517** [MachineMuse/MachineMusePowersuits#920] opened 2019-04-26 19:44 UTC
**Java**: 1.8.0_201
**Forge**: 1.12.2-14.23.5.2836

**Mods list**:
MachineMuse's Modular Powersuit (1.0.39)
Numina (1.0.36)
Redstone Flux (2.1.0.6)
RFTools (7.61)
McJtyLib (3.1.1)
Refined Storage (1.6.14)
Refined Storage Addons (0.4.4)

**Issue**:
The issue trigger when is installed the Kinetic Generator module on the Power Armor Leggings and it charges Wireless Crafting Grid (Refined Storage Additions).
The issue causes first a partial discharging and then the recharging of Wireless Crafting Grid.
It happens both on the client and on the server in survival mode only (no issues while in creative mode)

**Other**:
In [this video](https://streamable.com/u4ewv) I successfully charge the Wireless Crafting Grid in creative mode with the Kinetic Generator module and when i play in survival mode the module cause the discharging and the recharging of the Wireless Crafting Grid

I apologize if the explanation is not clear but English is not my native language

**Comment by eyeonus** [comment] 2019-04-27 08:16
This isn't exactly a bug. MPS is designed to be able to use external batteries, which it considers to be any item in the inventory that has power, such as your Grid.

What you're seeing is the Grid's energy being drained to power the Sprint Assist module you have on those legs, and then getting charged by the kinetic generator.

Now, I did see you have an Ultimate Battery installed in the legs as well, so I find it odd that the other two modules aren't using that instead. Apparently MPS doesn't prioritize battery modules over battery items.

That MPS doesn't prioritize installed battery modules over other inventory items for power usage and/or generation seems like a bug to me, but everything else is working as intended.

**Comment by eyeonus** [comment] 2019-04-27 08:21
This isn't exactly a bug. MPS is designed to be able to use external batteries, which it considers to be any item in the inventory that has power, such as your Grid.

What you're seeing is the Grid's energy being drained to power the Sprint Assist module you have on those legs, and then getting charged by the kinetic generator.

Now, I did see you have an Ultimate Battery installed in the legs as well, so I find it odd that the other two modules aren't using that instead. Apparently MPS doesn't prioritize battery modules over battery items.

That MPS doesn't prioritize installed battery modules over other inventory items for power usage and/or generation seems like a bug to me, but everything else is working as intended.

EDIT: On further inspection, it looks like it actually prioritizes:
1: Item in hand (right hand only, I'd guess, but possibly left as well?)
2: Installed battery modules.
3: Any other item in the player's inventory with a power capacity.

So I take it back. That prioritization precedence makes perfect sense, so unless my guess is wrong, this is not a bug at all.

**Comment by Blank517** [comment] 2019-04-27 14:55
OK, but I think if you had an item in your hand that you want to use you wouldn't want it to get discharged

**Comment by lehjr** [comment] 2019-04-28 13:42
While this is something that “can” be fixed, keep in mind that it’s impossible to meet everyone’s expectations. The simplest fix is a whitelist/blacklist, but the reality is that players expect things to work without much manual configuration. The next solution is to check to see if the item is an instance of IModularItem or if the item is an ItemTool or an ItemArmor and handle it that way. Unfortunately, this is a version specific fix, as the entire modular system for 1.13.2 is being rewritten. So not impossible, but the fix probably won’t surface until I fix it in both versions.

**Comment by lehjr** [comment] 2019-04-29 00:06
This should be fixed in Numina build 37.

**Closed as completed** 2019-04-30 19:42 UTC
