### ISSUE TITLE
[Bug]Heat bar doesn't work good

### ISSUE THREAD

**Issue by Xen1290** [MachineMuse/MachineMusePowersuits#605] opened 2015-08-30 21:38 UTC
@MachineMuse 
Step to reproduce:
1)Spam railgun
2)Done

I think only the number should increase, not the heat bar that goes out from the container texture
![test](https://cloud.githubusercontent.com/assets/8685029/9569599/28cd4ba4-4f70-11e5-8314-cc8a0a93d1f5.png)

I hope this ticket help you with the develop of this awesome mod!

**Comment by EzerArch** [comment] 2015-08-31 01:12
Honestly, when the temperature goes that high (not *that* high), the armor should explode and kill the player.

**Comment by MachineMuse** [comment] 2015-09-08 00:28
I still want to have some way to demonstrate how close the player is to being 'cooled off'. Ideas?

**Comment by aionys** [comment] 2015-09-08 01:38
None from me, but you can pretty easily make this particular problem be a LOT less likely by putting a reload time into the railgun- a fixed amount of time before it can be fired again.

Doesn't even have to be all that long- it just needs to be long enough that firing the railgun as fast as you can click the mouse is no longer possible.

**Comment by MachineMuse** [comment] 2015-09-08 03:18
Yeah, I guess it's pretty silly as-is. The TConstruct crossbow has a minimum reload time of 5 ticks and that's plenty fast enough.

**Comment by MachineMuse** [comment] 2015-09-08 03:39
I gave it a delay of 0.5 seconds and reduced the default heat generation (configs will need to be re-generated). That doesn't really change the problem of how the heat bar looks, but it'll reduce the cases where players produce an enormous amount of heat in little time. Heat was meant to be sort of a balancing factor for the high potential damage (25!) of the railgun, but it seems trivial to get that much damage from other mods these days without such drawbacks so it's no longer needed quite as much.

**Comment by EzerArch** [comment] 2015-09-08 06:36
1. Is it necessary you can fire the railgun just by holding down the fire key? It suits better in a machine-gun. Why not 1 shot per key press?

2. Limit the number of shots that can be fired in a row (8) and/or make it so each shot requires a cool-off time (5 or 10 ticks).

3. New HUD element: Green bars = ready; red bars = shots in cool-off state.
![2015-09-08_03 13 41](https://cloud.githubusercontent.com/assets/6743303/9727815/49edf9b8-55d9-11e5-8b9a-4dcb1a71d4f9.png)

**Comment by aionys** [comment] 2015-09-08 07:00
1. It IS one shot per press.

2. "... gave it a delay of 0.5 seconds...."

3. I don't think that's really needed....

**Comment by EzerArch** [comment] 2015-09-09 03:29
1) I can multi-shot by holding down the fire key.

2 and 3) *"I gave it a delay of 0.5 seconds (...) That __doesn't really change__ the problem of how the heat bar looks"*, and earlier *"I still want to have some way to __demonstrate__ how close the player is to being 'cooled off'. Ideas?"*. I think she is still open to ideas while the issue is still open. :)

**Comment by aionys** [comment] 2015-09-09 03:48
3 isn't, though. It's a HUD element showing whether the railgun is able to fire again, not an idea for how to show how close to not being so hot that wearing it damages the player the suit is, which is what she was asking for.

**Comment by aionys** [comment] 2015-09-09 03:49
And as for my response to 2, I was letting you know that MM /already did/ what you were suggesting with 2.

**Comment by MachineMuse** [comment] 2015-09-09 06:16
I could make it an asymptotic scale, so that the higher your heat is, the closer it gets to the top, and have a red marker in the middle or something to say 'don't go above this level'...

**Comment by aionys** [comment] 2015-09-09 06:27
I had an idea. How about using the heat color index? So instead of a bar, you have something that changes color based on the temperature. I don't know off the top of my head what the actual temperatures are, but when you heat something up, it goes through the spectrum from violet through blue, green, yellow, etc., and then eventually to white. Also if you're wearing something that's literally white hot, you're dead. No ifs, ands, or buts.

Give me a second, I'll look it up.

**Comment by aionys** [comment] 2015-09-09 06:29
http://www.interiorgardens.com/images/temperature-chart.jpg

**Comment by EzerArch** [comment] 2015-10-12 09:16
I like how this modder found out a way to indicate the "cool-off" process of every ability/tool in this mod (see the icons on the right): http://youtu.be/BkDHKSCp52A?t=2m23s

**Comment by MachineMuse** [comment] 2015-10-19 16:02
that type of 'cooldown' doesn't fit with how MPS handles heat internally, sadly.

**Comment by lehjr** [comment] 2017-05-01 11:26
This is finally fixed in beta 2 for 1.10.2. Basically, I just clamped the value for the meter:
https://github.com/MachineMuse/MachineMusePowersuits/blob/1.10.2-Java/src/main/java/net/machinemuse/powersuits/event/ClientTickHandler.java#L280

**Comment by lehjr** [comment] 2017-05-01 11:27
Closing this for now. If it needs more attention later we can revisit.

**Closed by lehjr** 2017-05-01 11:27 UTC
Labels: enhancement
