### ISSUE TITLE
No class found for ISound on server side?

### ISSUE THREAD

**Issue by sameer** [MachineMuse/MachineMusePowersuits#667] opened 2015-12-17 03:25 UTC
The following error results when using MMP (v. 0.11.0.284) on the server side. It occurs after a player crafts a MMP armor item. It seems as if MMP has mistaken the server for a client. My apologies if this has already been resolved in the latest version.

_Caused by: java.lang.ClassNotFoundException: net.minecraft.client.audio.ISound
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_66]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_66]
        at net.machinemuse.numina.sound.Musique.stopPlayerSound(Musique.scala) ~[Musique.class:?]
        at net.machinemuse.powersuits.powermodule.movement.JetPackModule.onPlayerTickInactive(JetPackModule.java:91) ~[JetPackModule.class:?]
        at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.apply(PlayerUpdateHandler.scala:51) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.class:?]
        at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.apply(PlayerUpdateHandler.scala:50) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$2.class:?]
        at scala.collection.Iterator$class.foreach(Iterator.scala:743) ~[Iterator$class.class:?]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1174) ~[AbstractIterator.class:?]
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[IterableLike$class.class:?]
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[AbstractIterable.class:?]
        at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:50) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.class:?]
        at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:37) ~[PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.class:?]
        at scala.collection.Iterator$class.foreach(Iterator.scala:743) ~[Iterator$class.class:?]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1174) ~[AbstractIterator.class:?]
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[IterableLike$class.class:?]
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[AbstractIterable.class:?]
        at net.machinemuse.powersuits.event.PlayerUpdateHandler.onPlayerUpdate(PlayerUpdateHandler.scala:37) ~[PlayerUpdateHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_257_PlayerUpdateHandler_onPlayerUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1517.UNOFFICIAL]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1517.UNOFFICIAL]
        at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:297) ~[ForgeHooks.class:1.7.10-1517.UNOFFICIAL]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1846) ~[sv.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:315) ~[yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:425) ~[mw.class:?]_

**Comment by Xen1290** [comment] 2015-12-17 06:00
MPS and Numina versions?

**Comment by sameer** [comment] 2015-12-17 10:40
@Xen1290 Build 284 and the associated Numina version provided by the CI server (0.4.0.131).

**Comment by lehjr** [comment] 2015-12-17 12:11
Duplicate of https://github.com/MachineMuse/MachineMusePowersuits/issues/660
Please make sure you are using the latest build before filing bug reports. Please make sure you check if the report has not already been filed. Thanks.

**Comment by Xen1290** [comment] 2015-12-17 12:21
As @lehjr said.

**Closed as completed** 2015-12-17 18:29 UTC

**Comment by sameer** [comment] 2015-12-18 04:00
Sorry about that!
