### ISSUE TITLE
Visual bug?

### ISSUE THREAD

**Issue by xJon** [MachineMuse/MachineMusePowersuits#887] opened 2019-01-03 09:05 UTC
Using v1.7.10-0.11.1.115-MaintenanceUpdate, when hovering over any of the 5 powersuit items in NEI, this huge description comes up which takes the whole screen:
![screenshot_1](https://user-images.githubusercontent.com/8945347/50629965-7b4c1d00-0f8a-11e9-8af3-864f896eaed2.png)
And when holding shift, it's even worse:
![screenshot_2](https://user-images.githubusercontent.com/8945347/50629966-856e1b80-0f8a-11e9-9022-ab0309b9d2e9.png)
Seems to be visual only and not effect these items when in the Tinker Table.

**Comment by TextureTurtle** [comment] 2019-01-16 20:40
Its not really a bug, its just that vanilla armors have lesser complexity than this Armour, so its hard to fit all of the extra details into the box. Also it has been this way for years.

**Comment by eyeonus** [comment] 2019-01-16 21:09
Just removing that last line, which is literally just a repeat of everything before but with all the line feeds removed, would solve this problem.

And I would say this is a bug, specifically because of that last line.

(No idea how to do that, but I'm sure lehjr has an idea or two.)

**Comment by lehjr** [comment] 2019-01-17 14:49
Edit: Confirmed. I'll look at it this weekend.

**Comment by lehjr** [comment] 2019-01-17 23:53
Fixed in next maintenance release

**Closed as completed** 2019-01-17 23:53 UTC
Labels: verified
