### ISSUE TITLE
Don't Work on Server

### ISSUE THREAD

**Issue by navaroneee** [MachineMuse/MachineMusePowersuits#741] opened 2016-12-07 15:50 UTC
I try to add this mod on my server, with the most newest versions from Numina and MPS, but the atributs dont change (up the baterry for exemple, thust of jetpack, All them), i try with others verions of both.
No log is created, becouse dont crash, just the armor dont change

Sorry my bad english

**Comment by navaroneee** [comment] 2016-12-07 16:20
I make some tests now, if i exclude everthing and puta again, its work on Offline, but when i enter on srv, dont work, and when i turn back to offline dont work either

**Comment by lehjr** [comment] 2016-12-07 16:57
Duplicate of https://github.com/MachineMuse/MachineMusePowersuits/issues/738

**Closed as completed by lehjr** 2016-12-07 16:57 UTC
