### ISSUE TITLE
[1.7.10] Advanced Solar Generator crash

### ISSUE THREAD

**Issue by MineWitherMC** [MachineMuse/MachineMusePowersuits#726] opened 2016-06-10 19:22 UTC
I was flying through deep ocean and found an island. I flew there and suddenly client froze and crashed.
Crash report: http://codepad.org/dqTZoGjH. As I see in crash report ASG crashed not finding biome BUT I can say I don't have mods adding biomes. Please help.

**Comment by lehjr** [comment] 2016-06-10 20:49
If this is something you can reproduce that would be helpful. Keep in mind that my ability to support 1.7.10 is incredibly limited due to all of my time dealing with rendering changes and working on supporting the next version of Minecraft (currently 1.9.4). It's literally just me working on the mod..  

Also keep in mind that 1.7.10 is a dangerous mix of abandoned and updated mods, with criss-crossing dependencies, and MPS for 1.7.10 has not had much in the way of updates for the past 6 months once again due to my lack of time to support multiple versions of Minecraft

**Comment by lehjr** [comment] 2017-05-06 12:47
Closing this since the crash log no longer applies due to code changes and the fact that this was not the latest version available when the bug report was filed. If this issue happens again in a future with a supported version, please create a new bug report.

**Closed as completed by lehjr** 2017-05-06 12:47 UTC
