### ISSUE TITLE
No recipe?

### ISSUE THREAD

**Issue by Kaisoul** [MachineMuse/MachineMusePowersuits#795] opened 2017-05-13 01:06 UTC
just installed ModularPowersuits-1.10.2-1.2.115
jei has no recipes at all for any item and i can't seem to figure out what's wrong...

**Comment by lehjr** [comment] 2017-05-13 01:10
Needs more information, like JEI version, forge version...

**Comment by Kaisoul** [comment] 2017-05-13 01:20
-k- one sec

**Comment by Kaisoul** [comment] 2017-05-13 01:21
forge-1.10.2-12.18.3.2297
jei_1.10.2-3.14.7.419

**Comment by Kaisoul** [comment] 2017-05-13 01:22
sorry about the lack of info was about half dead to the world do to my narcolepsy.

**Comment by lehjr** [comment] 2017-05-13 01:27
Updating my development environment to the newest versions. After that I'll see if I can find out why it isn't working.

**Comment by lehjr** [comment] 2017-05-13 02:18
Seems to be an issue with the recipes extracting and loading at the wrong times. Try closing the game and reloading it. I'll see if I can get this fixed in the next build.

**Comment by Kaisoul** [comment] 2017-05-13 02:21
i'll have to try that later on tonight gotta wait for my GF to get done playing in my Lan world to test that.

**Comment by TheGiddyLimit** [comment] 2017-05-13 10:31
+1 on this, using Forge 1.10.2//12.18.3.2264; JEI 1.10.2//3.14.7.416 with newest MPS (1.10.2//1.2.115)

**Comment by lehjr** [comment] 2017-05-13 12:24
The issue is that the recipes are beig extracted post-init by MPS, and being read during the same stage by Numina. So restarting the game will take care of that but it still needs to be fixed.

**Comment by lehjr** [comment] 2017-05-13 15:26
Fixed in the next release. Should be up shortly.

**Comment by Kaisoul** [comment] 2017-05-13 21:48
thanks for the fix i just gotta figure out when i get enough mats to build the table/parts how to pic the look of the suit like in the preview images.

**Closed as completed** 2018-08-28 12:35 UTC
