### ISSUE TITLE
Armor doesn't show on player model + equipped dont show either

### ISSUE THREAD

**Issue by Someaussie** [MachineMuse/MachineMusePowersuits#830] opened 2018-01-23 03:53 UTC
Installed the mod today and the armour doesn't show on my player model when equipped. The features are there like sprint boost etc just not the armour itself.
Also for some reason after installing the mod when i have an item in my hand it does not show on my player model

**Comment by lehjr** [comment] 2018-01-23 03:55
Not really enough information to address this.

**Comment by Someaussie** [comment] 2018-01-23 03:57
What else do you need?

**Comment by lehjr** [comment] 2018-01-23 04:02
Quote from the readme on the front page: 
"Be sure to include as much information as you can such as >>>LOGS<<<. I understand that not everyone is well versed in filing bug reports, but I simply will not guess what version of the mod you are using. I will not guess what other mods you have installed. Help me to help you. Seriously folks, these vauge bug reports are getting tiresome."

Modular powersuits has been around for several years, spanning many versions of Minecraft and has had many released versions. As such, it is impossible for me to tell what version of the mod or what version of Minecraft or forge you are using. Sometimes cause of the issue is apparent in the log, other times, not so much. But just telling me little more than "it doesn't work" will not be very helpful.

**Comment by Someaussie** [comment] 2018-01-23 04:34
Alright here's some more info
forge version: 12.18.2.2107
modular powersuits version: Final2
Other mods i have installed
Vics modern warfare v1.11.6 
Decocraft 2.4.2
Mrcrayfish furniture mod 4.1.2
Mrcrayfish skateboard mod 0.0.3
drugs galore 1.8.2
forgelin 1.5.2 
grappling hook mod 1.10.2
malisis advert 4.2.0
malisis core 4.3.0
moon core 3.5
security craft v1.8.3
better records 1.5.0
render player api 1.1
music craft 3.0.1
SoggyMustache's vehicles mod 1.1.5.2
log:
https://paste.ubuntu.com/26441941/
hope this helps :)

**Comment by eyeonus** [comment] 2018-01-23 05:02
Do you have any of the armor rendering modules installed? Do you have more than one installed? Did you go into the "Visual" gui and turn on any of the model parts?

The "Visual" gui looks like this:
http://www.mc-mod.net/wp-content/uploads/2017/03/Modular-Powersuits-Mod-9.jpg

**Comment by eyeonus** [comment] 2018-01-23 05:04
I'm not having this issue, so I don't think it's a bug.

**Comment by Someaussie** [comment] 2018-01-23 05:18
Opened the gui menu and nothing showed up.

Tried to place a tinker menu to try and do something and the game crashed here is the log
https://paste.ubuntu.com/26442183/

**Comment by lehjr** [comment] 2018-01-23 13:11
Regarding the crash, with a log I was able to find the issue in under a minute:
https://github.com/MachineMuse/MachineMusePowersuits/blob/803980bc7db071d6b76fc0ea43e2c94541c88493/src/main/java/net/machinemuse/powersuits/block/BlockTinkerTable.java#L67

The other issue starts at line ```15:25:25	net.minecraft.client.renderer.entity.RenderLivingBase	Couldn't render entity```

 caused by MrCrayfish's Skateboarding Mod

Edit: actually caused by RenderPlayerAPI-1.9.4-1.1.jar, which the skateboarding mod uses. There was a fix for this awhile back but it hasn't been used in a long time and is outdated. Support for it was dropped because adding support for it meant adding it as a dependency in the development environment, which is impossible when it doesn't exist at the time of porting. I will look into adding support back, but if it's it's not something I want to put a lot of time into and I can only add support if it can be done without making it a dependency.

**Comment by lehjr** [comment] 2018-01-23 16:06
Crash should be fixed in the next uploaded version. 
As for the issue with RenderPlayerAPI, got this almost done. Still working on syncing armor model yaw with the player model yaw.

**Comment by Someaussie** [comment] 2018-01-23 21:02
Thank you a lot for this i really appreciate your help

**Comment by lehjr** [comment] 2018-01-23 21:05
Yeah, so a little update on this. I can fix the armor model not rendering, but there are issues with the skateboard mod that will break it. It also breaks rendering for vanilla armor completely even without Modular Powersuits not installed.

**Comment by Someaussie** [comment] 2018-01-23 21:07
Oh ok alright then

**Comment by lehjr** [comment] 2018-01-23 23:17
I'll be uploading a fixed version of this mod shortly. I also have a fix for the skateboard mod and I'll send him the code for that in a few minutes as well.

**Comment by lehjr** [comment] 2018-01-24 00:03
OK, the Skateboard mod issue has been fixed with a pull request here: https://github.com/MrCrayfish/MrCrayfishSkateboardingMod/pull/6
New version of MPS is uploaded and should be visible "soon".

**Closed as completed** 2018-08-28 12:34 UTC
Labels: Other Mod's Fault (I think)
