### ISSUE TITLE
MPS armor not charging in IC2 chargers

### ISSUE THREAD

**Issue by willis936** [MachineMuse/MachineMusePowersuits#635] opened 2015-10-29 21:18 UTC
Tested with various voltage IC2 and GT battery buffers.  An "EU" field in the armor fills up but is only useful for charging tools and not keeping the MPS armor powered.

forge 1492
MPS 0.11.0.283
Numina 0.4.0.131
ic2 2.2.785
GT5U 5.08.32

**Comment by Xen1290** [comment] 2015-11-03 21:38
I can confirm that, also without GregTech

**Comment by EzerArch** [comment] 2015-11-04 01:57
Also Mekanism charge pads used to charge MPS armor, very long time ago.

**Comment by Tomino23** [comment] 2015-11-04 04:37
I'm having the same problem, Waila shows 2 seperate energy lines. one will fill up but there is no power.

**Comment by lehjr** [comment] 2015-11-06 18:20
I have to ask because I never tried it before, but did this work sometime in the past? If it did, it might have  been broken here https://github.com/MachineMuse/MachineMusePowersuits/commit/15cedbace4ea64ea87aed0ed0a03d15a78d1204d

In the past, I found Mekanism's charging pad to be too slow, at least for the quantum suit. I must admit that I never tried it for MPS. I used to use Thermal Expansion's energy infuser, but now I use EnderIO's wireless charger. It has a decent enough range and speed so you don't have to stop to charge up.

**Comment by Xen1290** [comment] 2015-11-06 20:56
Yes, in the past this worked. I think the same thing @lehjr , it's that commit.

**Comment by lehjr** [comment] 2015-11-07 18:23
I'll have to check that in a few days when I get time. I did test it a
couple days ago, and I did see what looks like 2 independent power buffers
being displayed, one in UE and one in RF. Not sure what it's supposed to
look like but I imagine that isn't it.

**Comment by lehjr** [comment] 2015-11-13 00:45
OK, so that commit I mentioned above was more or less reverted here: https://github.com/MachineMuse/MachineMusePowersuits/commit/18b3cbc357662cc64e70ef44f66d42500feac693

So meanwhile, I'm attempting to debug the issue.

**Comment by Xen1290** [comment] 2015-11-13 06:27
You Found it! Very good. Maybe you can make a pr?

**Comment by lehjr** [comment] 2015-11-13 11:51
It may be a couple of days. I'm working on setting up the fluid terminal to
handle older and latest builds of extra cells. I also added a minimum
Numina version too.

**Comment by Xen1290** [comment] 2015-11-13 13:30
Good! Thanks!

**Comment by lehjr** [comment] 2015-11-14 02:00
I have an experimental build that should solve this, just remember to back up your world before trying:
https://github.com/lehjr/MachineMusePowersuits/releases/tag/0.11.0.283c

**Comment by Xen1290** [comment] 2015-11-21 06:54
I think This is fixed with MPSA Merged @MachineMuse

**Comment by flowtender** [comment] 2015-11-25 01:29
Cool :)

**Closed by flowtender** 2015-11-25 01:29 UTC
