### ISSUE TITLE
Mass Power Drain Bug

### ISSUE THREAD

**Issue by Bulmanator** [MachineMuse/MachineMusePowersuits#510] opened 2014-08-28 22:00 UTC
A few friends and I have encountered a power drain bug on my private server. It occurs in both FTB and The Yogscast Complete pack. All I really know is it happens on my server when chunks are being loaded (causing server lag) and when the server lags we can have 1-2 Million power drained in an instant.
There is also another thing where it would lag and the heat gauge would max out and we would die to overheating.

Modular Powersuit Version: 1.6.4-0.10.0-118
Numina Version: 0.3.0.80
Powersuit Addons Version: 1.6.4-887
slick-util is also installed

Sorry for not providing more information but I don't really know what happens

**Comment by leagris** [comment] 2016-09-04 12:40
Getting this bug in 1.7.10, forge build 1614, ModularPowersuits-0.11.0.301.jar

**Comment by lehjr** [comment] 2016-09-04 18:27
There isn't enough information given to solve this issue. It could be an internal issue or a power API issue or an issue from other mods providing conflicting power API's . The mechanical assistance module does have quite a drain, especially if turned way up, but that doesn't sound like what's happening here. Unfortunately, the 1.7.10 workspace for MPS is such a beast to setup that unless I have enough information to investigate this further, I really can't put the time into it, especially with ALL of my free time currently going into the 1.10 build.

**Comment by leagris** [comment] 2016-09-06 13:23
If that can give clues: The amount of energy loss is proportional to the server lag.

**Comment by leagris** [comment] 2016-09-06 18:37
Given it drains all possible energy sources RF or EU. Enderio Vibrant Capacitor and Vajra from player inventory I think the issue is not with one or other energy API. At least not specific to IC2 or RF.

**Comment by lehjr** [comment] 2017-03-27 13:15
closing for now. If this problem persists in 1.10.2 we can revisit.

**Closed by lehjr** 2017-03-27 13:15 UTC
