### ISSUE TITLE
[1.7.10] Cannot View Powersuit Recipes in NEI

### ISSUE THREAD

**Issue by Whimsyturtle** [MachineMuse/MachineMusePowersuits#743] opened 2016-12-23 05:38 UTC
Logs: http://www.filedropper.com/fml-client-latest & http://www.filedropper.com/latest_2

(Reported on Behalf of Killer2000one)

**Comment by lehjr** [comment] 2016-12-23 12:32
Please use a real website, either Gist or pastebin.
Edit: 1 file is empty and one is over 11 MB. Also, the the versions you are using are not the latest. Please try the latest versions before reporting issues.

**Comment by cheatscom** [comment] 2017-02-14 22:11
I would like to elaborate on this issue further, I experience the same problem but ONLY when connecting to  a friend's server with my mod-pack, and they suffer the same issue when connecting to mine. The issue does not affect single player.

I am currently running ModularPowersuits-0.11.1.109, Numina-0.4.1.104 and NotEnoughItems-1.7.10-1.0.5.120-universal. I have made sure that the recipes are in the correct folder, and even changed the "auto-extract" option to true, but this does not make any difference. The version is still 1.7.10.

The recipes are still craft-able in multiplayer, but they are not visible in NEI. If there are any logs that are needed to help with this, please let me know. I'm not sure if this is a NEI issue or MP issue, but it would be nice to know.

**Comment by lehjr** [comment] 2017-02-15 12:51
Unfortunately, I cannot look into this at this time.

**Comment by lehjr** [comment] 2017-02-16 18:36
Should hopefully be fixed in Numina-0.4.1.105. File will be marked as beta for awhile until more testing is done.

**Comment by cheatscom** [comment] 2017-02-16 19:18
Thank you for your time. I appreciate that you would want to focus on 1.10, so thanks for continuing with this for now.

**Comment by EzerArch** [comment] 2017-02-17 01:17
Oopsy-daisy, the newest release (Numina 105 and MPS 110) broke some modules. Well, at least for me. For example, shock absorbers, shovel, axe modules are like they were set to zero, and the sliders have no effect.

Interestingly, I could view **all** NEI recipes in MPS109/Numina 104. Did the recipe format change? Perhaps, it's something on my side I could do/reset/regenerate the recipe files. I see no problem in downgrading. :)

Looks like @lehjr will need more coffee. ☕️ 

BTW, how's machinemuse?

**Comment by lehjr** [comment] 2017-02-17 04:46
I did some refactoring of the proxy stuff along with a slight alteration for the recipe loading. The recipe loading issue seemed to be limited to multiplayer games not using a dedicated server.

As far as how MachineMuse is doing, I wish I knew. My last communication with her was on here somewhere, months ago I believe.

**Comment by lehjr** [comment] 2017-02-17 04:52
Might be worth going back to the previous version of MPS until I get things sorted. Numina 105 should still be compatible. The problem is that in order to move the mod forward, I will have to end 1.7.10 support since it's just me. I was hoping to not leave off on a broken version. But there just isn't enough time in the day for one person to work on both.

**Comment by lehjr** [comment] 2017-02-17 17:38
OK, should be fixed in the next build. Hopefully this is the final build for 1.7.10

**Closed as completed** 2017-03-19 15:41 UTC
